# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

tone_instructions: "Professional, constructive, educational. Prioritize actionable feedback and best practices."

early_access: true

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: true
    base_branches:
      - main
      - develop
  path_instructions:
    - path: "src/github/**"
      instructions: |
        Review for proper GitHub API error handling, efficient pagination, token security,
        async/await, and GraphQL optimization.
    - path: "src/graph/**"
      instructions: |
        Review for cycle detection, thread safety, topological sorting, edge cases, and memory efficiency.
    - path: "src/agents/**"
      instructions: |
        Review for pool state management, race condition prevention, timeout handling, and Codegen SDK use.
    - path: "src/orchestrator/**"
      instructions: |
        Review asyncio patterns, deadlock prevention, and parallel execution performance.
    - path: "src/config.py"
      instructions: "Ensure Pydantic validation, sensible defaults, and env-var handling."
    - path: "tests/**"
      instructions: "Review test coverage, mocking, edge cases, and assertion clarity."
    - path: "*.yaml"
      instructions: "Check for valid YAML syntax, secure configuration, and proper structure."
    - path: "main.py"
      instructions: "Ensure signal handling, clean shutdown, CLI validation, and logging best practices."
  abort_on_close: true
  enable_auto_approval: false
  labels:
    reviewed: "coderabbit:reviewed"
    changes_requested: "coderabbit:changes-requested"
    critical: "coderabbit:critical"
  link_issues: true
  concise: false
  tools:
    ruff:
      enabled: true
    markdownlint:
      enabled: true
    yamllint:
      enabled: true
    shellcheck:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000
    languagetool:
      enabled: true
      enabled_only: true
      level: picky

chat:
  enabled: true
  auto_reply: true

knowledge_base:
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    
